### ISSUE TITLE
Jasco ZW4203 with Home Assistant reports firmware versin 5.53 is available, but after install, the version reported installed is still 5.52.

### ISSUE THREAD

**Issue by davislp** [zwave-js/firmware-updates#18]
The install succeeds, but the version is misreported.

**Comment by AlCalzone** [comment]
This report belongs into https://github.com/home-assistant/core/issues. The issue template would have guided you there btw.

**Comment by AlCalzone** [comment]
Ok nevermind, I see this is actually https://github.com/jascoproducts/firmware/issues/92. I thought it was a purely UI issue.
