### ISSUE TITLE
Issue PR#26: iblinds firmware updates

### ISSUE THREAD

**Issue by chancehiblinds** [zwave-js/firmware-updates#32]
Hey @AlCalzone , received your email on the issue. 
We have .gbl files hosted on our website but I am unable to find the documentation if .gbl files are compatible. 

e.g.
#26 
**Current that is failing:**
`"url": "https://gist.githubusercontent.com/habhomegit/b9101ec4b3e3b57dde31458f48055bd0/raw/a410973b437ac72d96930bb6faf7732cfbc6c827/iBlinds_V3.12.hex",`
`"integrity": "sha256:f0007bd8e41ebe12f05d06c90c1e0ae15581eb60a88ccd2802f63ac43b62261b"`

**Possible Solution:**
`"url": "https://support.myiblinds.com/wp-content/uploads/2021/09/iBlinds_v3.12_US.gbl",`

**Comment by AlCalzone** [comment]
Hi,

gbl files are supported. Could you open a PR to change the links and integrity in the existing files?

I'm on parental leave until the end of 2022, but I can merge a PR to fix this issue.
