### ISSUE TITLE
GE/Enbrighten 46201 / ZW4008 Firmware Problems

### ISSUE THREAD

**Issue by Morbidbystandard** [zwave-js/firmware-updates#57]
Hello,

After updating these nodes I lost power monitoring and the keypress 2X triggers the scene and the relay at the same time. Before the update, a double click would only trigger the scene.

Thanks

**Comment by AlCalzone** [comment]
Sounds like you need to report that to the manufacturer. They provide the firmware.

**Comment by Morbidbystandard** [comment]
Is there a way to remove the breaking update? Seems like something zwave-js should provide.

**Comment by AlCalzone** [comment]
Which version is it?

**Comment by AlCalzone** [comment]
No I mean which firmware version is the broken one?

**Comment by Morbidbystandard** [comment]
My apologies, the breaking firmware is 5.54

**Comment by Morbidbystandard** [comment]
I decided to report this issue to the manufacturer and came across this beta patch "0.54". Looks like they dropped the development for Home Assistant to recognize this as the most current update because the product line is obsolete. 

[ZW4008_Enbrighten-GE_46201_0.54 (1).zip](https://github.com/zwave-js/firmware-updates/files/11112899/ZW4008_Enbrighten-GE_46201_0.54.1.zip)

Un zip file, go to device, click the 3 dot menu, click update, then open .otz file, and update firmware.

The problem is zwave js sees this as an old firmware and prompts update.
