### ISSUE TITLE
Worng Version in firmware for Aeotec Range Exdendor 7

### ISSUE THREAD

**Issue by cpktmpkt** [zwave-js/firmware-updates#96]
there is a mistake in the version number of the range extender 7 from Aeotec. On their homepage is 1.0.5 published as the actual Version. In zwabe-js its numbered as 1.5.

see [https://aeotec.freshdesk.com/support/solutions/articles/6000244478-update-range-extender-7-v1-05](https://aeotec.freshdesk.com/support/solutions/articles/6000244478-update-range-extender-7-v1-05)

i tried to update via zwave-js an got an error, maybe that's the reason?

**Comment by Aeotec-ccheng** [comment]
@cpktmpkt V1.05 is the same as V1.5 where on our page we don't show the 3rd decimal so its actually V1.5.X:

V1.05 is the same as V1.5
V1.50 is not the same as V1.5

So in zwave-js V1.5 is correct. The third decimal doesn't matter much as we don't have multiple versions of V1.5
